matrix:
  include:
  - language: python
    python: 3.5
    before_install: cd vgridpy
    script: python3 setup.py test
    deploy:
      skip_cleanup: true
      provider: pypi
      user: wcrichto
      password:
        secure: Jx2GR2f0vPbQfVpfbfsOx0dqgS5IW30iwSvDGZt3hhUJcLHJTa6VmUc5Ozv65vR6diQIgBNTnWwkeyQlCMJcyuNwzM50QjQ7rwm7uLEq2MkrqRGTgrMUYuNG8MexG4L5n/wV5oIQ98/V2rjlF1p+oXwDdXNtCETpOOPCOVNRleuuoC8E1WX/umD3bWtnuq7hIUcExSQ9vFvhdKWUiDsiN5PaPX9rYFLIbjxBrgKU8fg8egYxUjiROF/U8NV57oY+XgJMvaii9frkVxeFaOpsgcfQusknh5jsiL4PGiKo0fDyjZRW41lTH0uxeBEz52WxIGj15ktW/WsYbyE043QLbVHV3wRaRZM/VlBOnTQOkbW1OXCLOB10XHCdwlazyD7J4HDHA7QITDD5AZM3GQhvNTHt+LHEaX9H42tIFekSgoEvIiJS3K7D0NT2J3jRY7sc6lqicZ+qyRl3P4MKpBkh9RsoaFyJsUBHldGlOtjfrr24TAB8uooAP46zGcT1g1osbWaOJHiEy0P6UTA1gm60eIPx24Lpx86uz3HaLj5hnXhNSbXgcygItlH+wWKbprPM+rIrYFAxPmzSrrB6X2ZXEzEYAqGORgeO7JnwwQxowoKBDl6dbeLL+/VQi7VwOVBKMcfOHpZa9HWGVl0qYim9U7i921aO59arQ2M20USRa+o=
      on:
        tags: true
        distributions: sdist bdist_wheel
  - language: node_js
    node_js: 10
    before_install: cd vgridjs
    install: npm install && npm run prepublishOnly
    before_deploy: npm run docs && touch docs/.nojekyll
    deploy:
    - provider: npm
      email: wcrichto@cs.stanford.edu
      api_key:
        secure: uMBZ60IQP+oXqNfuJk3yNc1ky2e0QpXon5NuLl9FLfJp7JobWkjBxvCyJ/xaSvGMUd8vsj59iSo/SGqgA7HkMcSqoXfzbmeHQibjM7E22M9TfWkZBxY9qfWlX1F720/kgSA9SMilGnEQ/7n/Yi0ZonGGEHd8WRvMCRWC4+kXVgxFZh1k6MAwlffwn97fVFb0lof4NQJuYbb5v2oCC3XOPj6h2+DS5g3Virnc/RrbB4xLfix0lDGgPWS1lWbc7d5WknafTYuqiSj8I+XD2Yzm5tYoPziB1XSUM4TB568e3/58b2HH3CCsxMLefHN6W0RCHR5UCrJJ8PopFIsMfPXQmEwP1KzQHscFo71mQ4dIshUIs6BnqCu/hjlqIkFC0SfurkpTMVTV/B5bob+ySi4WnumswiaRE5NmvSTbQpDxokCbTpdARCxNr7e/uJWGbd7nYY7ynlhCnCKdwbpjjyoJ3SDg8E8YzGgkpJvmoLbwL48G18KkON/HvPIFHCARbOoHno+4ZsthjmTg6SqRXj/X2hrVdh7yuM+XpWy9qU7NpL63zpgHHZ2FeYHOw6RmsbI8gf1jCa5ZTfT+wk/+r3mZkYcAHKEtXWaMm8J87YOq0QDWpGjGNV5hwenhUHDtnDZmcJ92W4VU09gw/0LJ98E4xqSx7P6P+f4MZPsjWVNRGKk=
      skip_cleanup: true
      on:
        tags: true
    - provider: pages
      skip_cleanup: true
      keep_history: true
      local_dir: vgridjs/docs
      github_token: "$GITHUB_TOKEN"
      on:
        branch: master
deploy:
