matrix:
  include:

  - language: python
    python: 3.5
    before_install: cd vgridpy
    script: python3 setup.py test
    deploy:
      skip_cleanup: true
      provider: pypi
      user: wcrichto
      password:
        secure: GtufzS8JePMkz3kgBfk5jUlEZXHjpFWYs893jU33n2Qcnfvz4ikpPl6xjEv9QCa0XZY5r8h4079NBXPMC3jUnHkEJ5jV4+K1/JlbS4ffTZNs+AIty3fvbUD5URrKKOAP/MTZl//XVWLnWhwjfutEEaza+S7vV/nHnzjGJooEw9FEGBGetTnWOfQXP8jPEu3HmLpjQWYk1Fiqq8YB7sng3FPwEfLtt/zNRzq5wCV5PPbmpAdYtqkBvdiX05xlkya+RsT+O02xjDM97tx+6qGDaLmEd/Mlt2CF/vZ+7M//fT/PbAQHpa+mw7e5kBxFZ1mFQcOfaSqfFKc21iYw/g50MnzxRfTrrssfpGY3zs7xM+Q9JdG9SyVcygTXxKhCQ9NxWFEqjDrgxWB3K45iRqtg1girFsh8ujzNJRltrN3MFep0hQgP+FURnqD633co2Eagr2yLVlwDeD/UBSNpSOsS6wGQFNSmSs1Z1Q1/p3K/pnIRolQkTRMlGuE5FjyRYyXKCa6/5+aMyoh40eZPl1UZv4cKlTTk0SzewmZTM5NVx3i2iBKKFl4RxQyR6lIzV6J7B5r8MkaIm6h+GbF43q4Qct9YsCORL+dgu1FliiMXgV5vCwrv409ywLqHzZFR10WinvndY97YX9657Alpk+NhuTbdxpM787raAdiTYduywW8=
      on:
        tags: true
        distributions: sdist bdist_wheel

  - language: node_js
    node_js: 10
    before_install: cd vgridjs
    install: npm install && npm run prepublishOnly
    deploy:
      provider: npm
      email: wcrichto@cs.stanford.edu
      api_key:
        secure: uMBZ60IQP+oXqNfuJk3yNc1ky2e0QpXon5NuLl9FLfJp7JobWkjBxvCyJ/xaSvGMUd8vsj59iSo/SGqgA7HkMcSqoXfzbmeHQibjM7E22M9TfWkZBxY9qfWlX1F720/kgSA9SMilGnEQ/7n/Yi0ZonGGEHd8WRvMCRWC4+kXVgxFZh1k6MAwlffwn97fVFb0lof4NQJuYbb5v2oCC3XOPj6h2+DS5g3Virnc/RrbB4xLfix0lDGgPWS1lWbc7d5WknafTYuqiSj8I+XD2Yzm5tYoPziB1XSUM4TB568e3/58b2HH3CCsxMLefHN6W0RCHR5UCrJJ8PopFIsMfPXQmEwP1KzQHscFo71mQ4dIshUIs6BnqCu/hjlqIkFC0SfurkpTMVTV/B5bob+ySi4WnumswiaRE5NmvSTbQpDxokCbTpdARCxNr7e/uJWGbd7nYY7ynlhCnCKdwbpjjyoJ3SDg8E8YzGgkpJvmoLbwL48G18KkON/HvPIFHCARbOoHno+4ZsthjmTg6SqRXj/X2hrVdh7yuM+XpWy9qU7NpL63zpgHHZ2FeYHOw6RmsbI8gf1jCa5ZTfT+wk/+r3mZkYcAHKEtXWaMm8J87YOq0QDWpGjGNV5hwenhUHDtnDZmcJ92W4VU09gw/0LJ98E4xqSx7P6P+f4MZPsjWVNRGKk=
      skip_cleanup: true # Don't clean/reset working directory
      on:
        tags: true
