matrix:
  include:
  - language: python
    python: 3.5
    before_install: cd vgridpy
    script: python3 setup.py test
    deploy:
      skip_cleanup: true
      provider: pypi
      user: wcrichto
      password:
        secure: UrwGnrRHQBAGSkVuu4MVR27iaws3E5z/TdatQ5mBWS8wiOXKa2KCw3Rj1aDExbDcSDqvbvTul5YY0dmZ5iDgNRZ0GelRBEX32EvnoKTATuntTwpYXsAOv6kuH77ztsxHaQFirknizetWxpZ7ZfWCmz/eLrlTRqGjzKQ0DVWGnMDIlYDHOuZN15yI1DAXmaBeHTGQCaJqxZnhrDblXni9bP1hF/PeMBwkzN58QhD4zeLxa6NXZuEHOdM4JEVypPmLtpOaQqbz7cHwcl9LiLu4UbjFrBPgipzN9JfN4wiDYnj649IWILS4HNtrcLrCzh5RmJKQKGR2lnDkxt5PIV5owOqolDkKSnrXDl+cfFidrUp0x1uq20LEfIUqJMVeAPDfjxoteiCkBvEG54HQg2OTAS6qgKu4/tbBSKIhO5ZW3RgU+EnEfL+DsFx7JVAG5i6Jg5ds9p9DB6i5m9vCrx0U8Na8Xuw4PpLu0jZvRVxHYM6YKbxm++QxJuiOFe4PII7UBAXlamjWBV0zGGpspXeR6nd+vwCx7p0rtbjVYJW8d+9yCA8lAaIONwG92IrBa7F6xfxuOP8AbfPywpfpc3B/MKqVuaJnp45KizA8uFNVyYavgDzaiybVs4JkOR37pXK1xpdrdh6x6OSviBPsBxAd3BvwOcWbSvD4yUvXrJYqYqk=
      on:
        tags: true
        distributions: sdist bdist_wheel
  - language: node_js
    node_js: 10
    before_install: cd vgridjs
    install: npm install && npm run prepublishOnly
    deploy:
    - provider: npm
      email: wcrichto@cs.stanford.edu
      api_key:
        secure: uMBZ60IQP+oXqNfuJk3yNc1ky2e0QpXon5NuLl9FLfJp7JobWkjBxvCyJ/xaSvGMUd8vsj59iSo/SGqgA7HkMcSqoXfzbmeHQibjM7E22M9TfWkZBxY9qfWlX1F720/kgSA9SMilGnEQ/7n/Yi0ZonGGEHd8WRvMCRWC4+kXVgxFZh1k6MAwlffwn97fVFb0lof4NQJuYbb5v2oCC3XOPj6h2+DS5g3Virnc/RrbB4xLfix0lDGgPWS1lWbc7d5WknafTYuqiSj8I+XD2Yzm5tYoPziB1XSUM4TB568e3/58b2HH3CCsxMLefHN6W0RCHR5UCrJJ8PopFIsMfPXQmEwP1KzQHscFo71mQ4dIshUIs6BnqCu/hjlqIkFC0SfurkpTMVTV/B5bob+ySi4WnumswiaRE5NmvSTbQpDxokCbTpdARCxNr7e/uJWGbd7nYY7ynlhCnCKdwbpjjyoJ3SDg8E8YzGgkpJvmoLbwL48G18KkON/HvPIFHCARbOoHno+4ZsthjmTg6SqRXj/X2hrVdh7yuM+XpWy9qU7NpL63zpgHHZ2FeYHOw6RmsbI8gf1jCa5ZTfT+wk/+r3mZkYcAHKEtXWaMm8J87YOq0QDWpGjGNV5hwenhUHDtnDZmcJ92W4VU09gw/0LJ98E4xqSx7P6P+f4MZPsjWVNRGKk=
      skip_cleanup: true
      on:
        tags: true
    - provider: pages
      before_deploy: npm run docs
      skip_cleanup: true
      keep_history: true
      local_dir: docs
      github_token:
        secure: IPikrZUelstJ3+vA7+mRXjAlKbT2ZKzDxAqcOO+Zjq1anBnGmahOiggkhM2tOmI3oYtfN2sr14d2S+UIoOMPYTp/pqOiiA/FJS1BfpueMxAj73Lh+N3AMJiK1yZDY2XR2wWfKLviYaJ2mv3MqTWdnAJgh9iEYv89hy4C/y4XcRikUtE4dzj4Ti0APrO0x/eFgIW6q/Qnyhdx2IlsAMOZJ5xOomk9gzGM+CTo9XrFRt6RzXP9oP2HspQpe55zVOQ3dKFmiwo5n//r78JjGPXd7nuU/pwq0uKvmiwGxw/aTNJV0fGabEFTVvxZnqKQuiCssmiUSfBlS/yvN1GZiTnRj7tZlMHE4SXj5zc09YrNFzlylbK+kEBKimd3k+CzWrDWserPOFidvgPiFITp+MmPfDovxpIhVUnsdYPoFTCNcuAKQdPo0+O5cvJNoZVpteXvORLlekt89EHtNfwDeMUWMSO7mrVUq7P0eVxRc72fBvvVbv0G1pwOFuDFI1+yKUbEXuHNAq+G/1pZ7lCQPyOrJmXQ6nReuI0hiSGESKROj4nR6g/H9axkDWC0M7LZ3l00A0sIDJZFpVBtCBDMB1s0nQCrxDl4axZyIP+kA7/Kkouk0I0KpNS06ihR2+PZIFgZxlWAx7kVVvOWpHxdR6Pvl0UGCkhsEifs8p5yBh51kkc=
      on:
        branch: master
